service: redis-lambda
plugins:
  - serverless-dotenv-plugin
custom:
  dotenv:
    path: ./.env
    include:
      - REDIS_PORT
      - REDIS_HOSTNAME
      - REDIS_PASSWORD
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: 'us-east-1'
  memorySize: 512
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "logs:*"
        - "ec2:*"
      Resource: '*'
functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: api/{id}
          method: GET
          cors: true